---
name: Lint Codebase

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
    lint:
      name: Lint Code Base
      uses: CGBassPlayer/sicas-workflows/.github/workflows/lint.yml@main
      with:
        default_branch: master
